name: Build and push Docker image

on:
  push:
    branches:
      - master
env:
  PROJECT_ID: vivid-poet-373515
  IMAGE: configuration-api
  DOCKER_BUILD_PUSH: true
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Google Cloud Platform
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ secrets.GCR_SERVICE_ACCOUNT_KEY }}
        export_default_credentials: true
        
    - name: Login to Docker Registry
      uses: docker/login-action@v1
      with:
        registry: gcr.io
        username: _json_key
        password: ${{ secrets.GCR_SERVICE_ACCOUNT_KEY }}
        
    - name: Check if Dockerfile exists
      run: |
        if [ ! -f "${GITHUB_WORKSPACE}/src/ConfigurationApi/Dockerfile" ]; then
          echo "Dockerfile not found at ${GITHUB_WORKSPACE}/src/ConfigurationApi/Dockerfile. Please check again"
          exit 1
        fi
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./src/ConfigurationApi/Dockerfile
        push: true
        tags: gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE }}:${{ github.sha }}
