name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - master

env:
  PROJECT_ID: vivid-poet-373515
  IMAGE: gcr.io/vivid-poet-373515/configuration-api

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure gcloud
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ secrets.GCR_SERVICE_ACCOUNT_KEY }}
        export_default_credentials: true

    - name: Build and push image
      uses: docker/build-push-action@v2
      with:
        context: .
        dockerfile: ./src/ConfigurationApi/Dockerfile
        push: true
        tags: ${{ env.IMAGE }}
